Create build time dependencies sample app
badoo/RIBs pull request #248
Opened 2021-02-02 10:41 UTC by LachlanMcKee

**Description**:
Create a sample app with basic build time dependencies usage, where it creates a child node with arguments passed via the view's factory.

2021-02-02 20:03 UTC, zsoltk requested changes

2021-02-02 20:03 UTC, zsoltk commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/routing/BuildTimeDepsParentRouter.kt
> +            is Default -> Resolution.noop()
```suggestion
            is Default -> noop()
```

2021-02-02 20:03 UTC, zsoltk commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/profile/BuildTimeDepsProfile.kt
> +interface BuildTimeDepsProfile : Rib {
```suggestion
interface Profile : Rib {
```

2021-02-02 20:03 UTC, zsoltk commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/BuildTimeDepsParent.kt
> +interface BuildTimeDepsParent : Rib
```suggestion
interface BuildTimeDeps : Rib
```

2021-02-02 20:10 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/BuildTimeDepsParentInteractor.kt
> +                        // Typically occurs when an invalid integer was input.
Good catch. This was previously possible when using an EditText rather than the spinner

2021-02-03 08:47 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/profile/BuildTimeDepsProfileView.kt
> +        profileLabel.text = "This is the profile RIB built for user: $profileId"
done

2021-02-03 11:16 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/routing/BuildTimeDepsParentRouter.kt
> +package com.badoo.ribs.samples.buildtime.parent.routing
done

2021-02-03 11:16 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/builder/BuildTimeDepsParentBuilder.kt
> +package com.badoo.ribs.samples.buildtime.parent.builder
done

2021-02-03 11:16 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/profile/BuildTimeDepsProfile.kt
> +interface BuildTimeDepsProfile : Rib {
done

2021-02-03 11:16 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/BuildTimeDepsParent.kt
> +interface BuildTimeDepsParent : Rib
done

2021-02-03 11:17 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/parent/BuildTimeDepsParent.kt
> +package com.badoo.ribs.samples.buildtime.parent
done

2021-02-03 11:17 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/profile/builder/BuildTimeDepsProfileBuilder.kt
> +package com.badoo.ribs.samples.buildtime.profile.builder
done

2021-02-03 11:17 UTC, LachlanMcKee commented on samples/build-time-dependencies/src/main/java/com/badoo/ribs/samples/buildtime/profile/BuildTimeDepsProfile.kt
> +package com.badoo.ribs.samples.buildtime.profile
done

2021-02-03 19:21 UTC, zsoltk approved these changes

2021-02-03 19:22 UTC, merged