Sucesive backstack operation bug fix
badoo/RIBs pull request #276
Opened 2021-03-12 13:30 UTC by SamuPS

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/dialogkeyboard/AlertDialogKeyboardTest.kt
> +class AlertDialogKeyboardTest {
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/BaseNodesTest.kt
> +            val buildParams = BuildParams<TestRootBuilder.Params>(
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/RootNodeLifecycleTest.kt
> +                payload = TestRootBuilder.Params(false),
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/child/TestChildInteractor.kt
> +    buildParams: BuildParams<*>
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/child/TestChildView.kt
> +    context: Context,
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/child/TestChildView.kt
> +        FrameLayout(context, attrs, defStyle).also {
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/child/builder/TestChildBuilder.kt
> +    class Params(
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/root/TestRoot.kt
> +            block: (TestNode<TestChildView>) -> Unit
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/root/TestRootInteractor.kt
> +    buildParams: BuildParams<*>,
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/root/builder/TestRootBuilder.kt
> +    )
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/AlertDialogLauncher.kt
> +            dialogs.clear()
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/AlertDialogLauncher.kt
> +        dialogs.remove(dialog)
This is already in master, this shouldn't be showed in the diff.

2021-04-12 13:17 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/DialogExtensions.kt
> +                setOnDismissListener { this@toAlertDialog.rib = null }
This is already in master, this shouldn't be showed in the diff.

2021-04-19 13:26 UTC, zsoltk requested changes

2021-04-19 13:26 UTC, zsoltk commented on libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/Actor.kt
> +    private fun canTransition(params: TransactionExecutionParams<C>) = params.globalActivationLevel != SLEEPING && transitionHandler != null
```suggestion
    private fun <C : Parcelable> PendingTransition<C>.isScheduled(state: WorkingState<C>) = 
        this in state.pendingTransitions

    private fun canTransition(params: TransactionExecutionParams<C>) = 
        params.globalActivationLevel != SLEEPING && transitionHandler != null
```

2021-04-19 13:26 UTC, zsoltk commented on libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/PendingTransitionFactory.kt
> +    fun make(
`create`?

2021-04-19 13:26 UTC, zsoltk commented on libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/RoutingStatePool.kt
> +    private fun discardPendingTransitions(pendingTransition: List<PendingTransition<C>>) {
```suggestion
    private fun cancelPendingTransitions(pendingTransition: List<PendingTransition<C>>) {
```

2021-04-19 13:26 UTC, zsoltk commented on libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/feature/ActorTest.kt
> +     * [Case-1]
```suggestion
     * [Case-2]
```

2021-04-19 15:57 UTC, zsoltk approved these changes

2021-04-19 17:49 UTC, merged