Create Permissions sample application
badoo/RIBs pull request #283
Opened 2021-04-08 21:53 UTC by KovalevAndrey

**Description**: Create Permissions sample application by extracting some part of code from sandbox app and simplify things  by removing MVI, RxJava, etc. dependencies 

**Related issue(s)**:

2021-04-09 16:50 UTC, zsoltk requested changes

2021-04-09 16:50 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/PermissionsPresenter.kt
> +                            }
You could extract this block, it's a bit too much here

2021-04-09 16:50 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/PermissionsPresenter.kt
> +        private val permissionRequester: PermissionRequester,
Could you please set continuation indent to 4 spaces and reformat all files

2021-04-09 16:50 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/PermissionsRib.kt
> +interface PermissionsRib : Rib {
```suggestion
interface PermissionsSample : Rib {
```

No need to mention Rib in the actual name. (Also, you can use the plugin to rename every file in a Rib automatically, no need to do one by one)

2021-04-09 16:50 UTC, zsoltk commented on settings.gradle
> +include ':samples:android-integration:permissions'
Can you please keep them organised by alphabetical order, thanks.

2021-04-12 08:31 UTC, KovalevAndrey commented
I have fixed the comments first and now extending the functional to having a child RIB that will be receiving permissions callback

2021-04-12 13:06 UTC, KovalevAndrey commented
> I have fixed the comments first and now extending the functional to having a child RIB that will be receiving permissions callback

Created child RIB that uses permission while parent RIB doesn't

2021-04-19 21:11 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/PermissionsPresenter.kt
> +                            }
You resolved but it remained the same :)

2021-04-19 21:12 UTC, zsoltk commented on settings.gradle
> +include ':samples:android-integration:permissions'
Same here.

2021-04-19 21:13 UTC, zsoltk commented on settings.gradle
> +include ':samples:android-integration:permissions'
My bad.

2021-04-19 21:13 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/PermissionsPresenter.kt
> +                            }
My bad!

2021-05-22 11:47 UTC, zsoltk commented on samples/android-integration/permissions/src/main/java/com/badoo/ribs/samples/permissions/rib/parent/PermissionsSampleParentView.kt
> +            else -> super.getParentViewForSubtree(subtreeOf)
This is super hacky :) Normally we should simply rely on incoming interface, but yes, now they are the same. Let's try to figure out something for this.

2021-06-17 14:18 UTC, zsoltk approved these changes

2021-06-17 14:37 UTC, merged