Upgrade to Gradle 7 and fix breaking changes
badoo/RIBs pull request #301
Opened 2021-05-08 11:56 UTC by antonshilov

**Description**:
To use latest AGP for Jetpack Compose builds we need to upgrade to Gradle 7. But it has remove "maven" plugin and some other tasks related to artifact publishing. So I had to migrate and update some dependencies.
I am not 100% I did this correctly so maybe we can try publishing to see if it works.

**Related issue(s)**:

2021-05-10 11:00 UTC, technoir42 commented on tooling/rib-intellij-plugin/build.gradle
> +                url = "file://" + new File(System.getProperty("user.home"), ".m2/repository").absolutePath
This branch is unnecessary as you can always publish there using `publishToMavenLocal`. I suggest rewriting like this:
```
if (hasMavenCredentials()) {
    maven {
        ...
    }
}
```

2021-05-10 11:05 UTC, technoir42 requested changes

2021-05-10 11:05 UTC, technoir42 commented on tooling/rib-intellij-plugin/build.gradle
> +build.dependsOn publishing
A task called `publishing` doesn't exist. Tbh it's strange that `build` publishes something. Usually `build` assembles all artifacts and runs all checks. Publishing is done separately in most open source libraries that I came across.

2021-06-07 17:04 UTC, zsoltk approved these changes

2021-06-07 17:04 UTC, merged