Update Compose to 1.0-rc02 and update required dependencies
badoo/RIBs pull request #323
Opened 2021-07-16 17:48 UTC by idyatlov

**Description**:

- Update to Kotlin 1.5.21 and update required dependencies
- Make AndroidX dependencies versions explicit in case of Compose
- Use AGP 4.2.2 instead of different AGP versions
- Set compileSdk and targetSdk to 30, update Robolectric
- Move to kotlin-parcelize instead of removed kotlin-android-extensions
- Remove jcenter() from repositories list
- Use JUnit5 automatic extension loading to fix unit tests errors due isMainThread() check
- Convert failed tests to JUnit5

**Related issue(s)**:

2021-07-16 18:15 UTC, idyatlov commented on libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/PendingTransition.kt
> +    private val handler: Handler = Handler(Looper.getMainLooper())
Please check this, do we really need Handler()? It can be created not on the main thread in that case

2021-07-19 10:01 UTC, CherryPerry requested changes

2021-07-19 20:09 UTC, idyatlov commented on gradle/dependencies.gradle
> +println("androidxCoreVersion version: ${versions.androidxCoreVersion}")
It's already printing at dependencies.gradle:16

2021-07-20 09:55 UTC, idyatlov commented on libraries/rib-base-test/build.gradle
> +    compileOnly deps.test.junitApi
Added module [here](https://github.com/badoo/RIBs/pull/323/commits/5f72fb4adf4a3fc652c93168cbfc22b0d0ca1b1d)

2021-07-20 10:43 UTC, CherryPerry approved these changes

2021-07-20 11:40 UTC, merged